from django import forms

LANGUAGE_CHOICES = [
    ('ar-eg', 'Arabic (Egypt)'),
    ('ar-sa', 'Arabic (Saudi Arabia)'),
    ('bg-bg', 'Bulgarian'),
    ('ca-es', 'Catalan'),
    ('zh-cn', 'Chinese (China)'),
    ('zh-hk', 'Chinese (Hong Kong)'),
    ('zh-tw', 'Chinese (Taiwan)'),
    ('hr-hr', 'Croatian'),
    ('cs-cz', 'Czech'),
    ('da-dk', 'Danish'),
    ('nl-be', 'Dutch (Belgium)'),
    ('nl-nl', 'Dutch (Netherlands)'),
    ('en-au', 'English (Australia)'),
    ('en-ca', 'English (Canada)'),
    ('en-gb', 'English (Great Britain)'),
    ('en-in', 'English (India)'),
    ('en-ie', 'English (Ireland)'),
    ('en-us', 'English (United States)'),
    ('fi-fi', 'Finnish'),
    ('fr-ca', 'French (Canada)'),
    ('fr-fr', 'French (France)'),
    ('fr-ch', 'French (Switzerland)'),
    ('de-at', 'German (Austria)'),
    ('de-de', 'German (Germany)'),
    ('de-ch', 'German (Switzerland)'),
    ('el-gr', 'Greek'),
    ('he-il', 'Hebrew'),
    ('hi-in', 'Hindi'),
    ('hu-hu', 'Hungarian'),
    ('id-id', 'Indonesian'),
    ('it-it', 'Italian'),
    ('ja-jp', 'Japanese'),
    ('ko-kr', 'Korean'),
    ('ms-my', 'Malay'),
    ('nb-no', 'Norwegian'),
    ('pl-pl', 'Polish'),
    ('pt-br', 'Portuguese (Brazil)'),
    ('pt-pt', 'Portuguese (Portugal)'),
    ('ro-ro', 'Romanian'),
    ('ru-ru', 'Russian'),
    ('sk-sk', 'Slovak'),
    ('sl-si', 'Slovenian'),
    ('es-mx', 'Spanish (Mexico)'),
    ('es-es', 'Spanish (Spain)'),
    ('sv-se', 'Swedish'),
    ('ta-in', 'Tamil'),
    ('th-th', 'Thai'),
    ('tr-tr', 'Turkish'),
    ('vi-vn', 'Vietnamese')
]


VOICE_CHOICES = [
    ('Eka', 'Eka (Female, English India)'),
    ('Jai', 'Jai (Female, English India)'),
    ('Ajit', 'Ajit (Male, English India)'),
    ('Linda', 'Linda (Female, English United States)'),
    ('Amy', 'Amy (Female, English United States)'),
    ('Mary', 'Mary (Female, English United States)'),
    ('John', 'John (Male, English United States)'),
    ('Mike', 'Mike (Male, English United States)'),
    ('Puja', 'Puja (Female, Hindi)'),
    ('Kabir', 'Kabir (Male, Hindi)'),
    ('Oda', 'Oda (Female, Arabic Egypt)'),
    ('Salim', 'Salim (Male, Arabic Saudi Arabia)'),
    ('Dimo', 'Dimo (Male, Bulgarian)'),
    ('Rut', 'Rut (Female, Catalan)'),
    ('Luli', 'Luli (Female, Chinese China)'),
    ('Shu', 'Shu (Female, Chinese China)'),
    ('Chow', 'Chow (Female, Chinese China)'),
    ('Wang', 'Wang (Male, Chinese China)'),
    ('Jia', 'Jia (Female, Chinese Hong Kong)'),
    ('Xia', 'Xia (Female, Chinese Hong Kong)'),
    ('Chen', 'Chen (Male, Chinese Hong Kong)'),
    ('Akemi', 'Akemi (Female, Chinese Taiwan)'),
    ('Lin', 'Lin (Female, Chinese Taiwan)'),
    ('Lee', 'Lee (Male, Chinese Taiwan)'),
    ('Nikola', 'Nikola (Male, Croatian)'),
    ('Josef', 'Josef (Male, Czech)'),
    ('Freja', 'Freja (Female, Danish)'),
    ('Daan', 'Daan (Male, Dutch Belgium)'),
    ('Lotte', 'Lotte (Female, Dutch Netherlands)'),
    ('Bram', 'Bram (Male, Dutch Netherlands)'),
    ('Zoe', 'Zoe (Female, English Australia)'),
    ('Isla', 'Isla (Female, English Australia)'),
    ('Evie', 'Evie (Female, English Australia)'),
    ('Jack', 'Jack (Male, English Australia)'),
    ('Rose', 'Rose (Female, English Canada)'),
    ('Clara', 'Clara (Female, English Canada)'),
    ('Emma', 'Emma (Female, English Canada)'),
    ('Mason', 'Mason (Male, English Canada)'),
    ('Alice', 'Alice (Female, English Great Britain)'),
    ('Nancy', 'Nancy (Female, English Great Britain)'),
    ('Lily', 'Lily (Female, English Great Britain)'),
    ('Harry', 'Harry (Male, English Great Britain)'),
    ('Oran', 'Oran (Male, English Ireland)'),
    ('Aada', 'Aada (Female, Finnish)'),
    ('Emile', 'Emile (Female, French Canada)'),
    ('Olivia', 'Olivia (Female, French Canada)'),
    ('Logan', 'Logan (Female, French Canada)'),
    ('Felix', 'Felix (Male, French Canada)'),
    ('Bette', 'Bette (Female, French France)'),
    ('Iva', 'Iva (Female, French France)'),
    ('Zola', 'Zola (Female, French France)'),
    ('Axel', 'Axel (Male, French France)'),
    ('Theo', 'Theo (Male, French Switzerland)'),
    ('Lukas', 'Lukas (Male, German Austria)'),
    ('Hanna', 'Hanna (Female, German Germany)'),
    ('Lina', 'Lina (Female, German Germany)'),
    ('Jonas', 'Jonas (Male, German Germany)'),
    ('Tim', 'Tim (Male, German Switzerland)'),
    ('Neo', 'Neo (Male, Greek)'),
    ('Rami', 'Rami (Male, Hebrew)'),
    ('Mate', 'Mate (Male, Hungarian)'),
    ('Intan', 'Intan (Male, Indonesian)'),
    ('Bria', 'Bria (Female, Italian)'),
    ('Mia', 'Mia (Female, Italian)'),
    ('Pietro', 'Pietro (Male, Italian)'),
    ('Hina', 'Hina (Female, Japanese)'),
    ('Airi', 'Airi (Female, Japanese)'),
    ('Fumi', 'Fumi (Female, Japanese)'),
    ('Akira', 'Akira (Male, Japanese)'),
    ('Nari', 'Nari (Female, Korean)'),
    ('Aqil', 'Aqil (Male, Malay)'),
    ('Marte', 'Marte (Female, Norwegian)'),
    ('Erik', 'Erik (Male, Norwegian)'),
    ('Julia', 'Julia (Female, Polish)'),
    ('Jan', 'Jan (Male, Polish)'),
    ('Marcia', 'Marcia (Female, Portuguese Brazil)'),
    ('Ligia', 'Ligia (Female, Portuguese Brazil)'),
    ('Yara', 'Yara (Female, Portuguese Brazil)'),
    ('Dinis', 'Dinis (Male, Portuguese Brazil)'),
    ('Leonor', 'Leonor (Female, Portuguese Portugal)'),
    ('Doru', 'Doru (Male, Romanian)'),
    ('Olga', 'Olga (Female, Russian)'),
    ('Marina', 'Marina (Female, Russian)'),
    ('Peter', 'Peter (Male, Russian)'),
    ('Beda', 'Beda (Male, Slovak)'),
    ('Vid', 'Vid (Male, Slovenian)'),
    ('Juana', 'Juana (Female, Spanish Mexico)'),
    ('Silvia', 'Silvia (Female, Spanish Mexico)'),
    ('Teresa', 'Teresa (Female, Spanish Mexico)'),
    ('Jose', 'Jose (Male, Spanish Mexico)'),
    ('Camila', 'Camila (Female, Spanish Spain)'),
    ('Sofia', 'Sofia (Female, Spanish Spain)'),
    ('Luna', 'Luna (Female, Spanish Spain)'),
    ('Diego', 'Diego (Male, Spanish Spain)'),
    ('Molly', 'Molly (Female, Swedish)'),
    ('Hugo', 'Hugo (Male, Swedish)'),
    ('Sai', 'Sai (Male, Tamil)'),
    ('Ukrit', 'Ukrit (Male, Thai)'),
    ('Omer', 'Omer (Male, Turkish)'),
    ('Chi', 'Chi (Male, Vietnamese)')
]



class TextToSpeechForm(forms.Form):
    text = forms.CharField(
        label='Text',
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Please enter the text you wish to convert into audio in your preferred language...'
        })
    )
    language_code = forms.ChoiceField(
        label='Language',
        choices=LANGUAGE_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    voice_code = forms.ChoiceField(
        label='Voice',
        choices=VOICE_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
